# Generated by Django 3.0 on 2019-12-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_telepon', models.CharField(max_length=30)),
                ('bidang', models.CharField(max_length=300)),
                ('jadwal_praktek', models.DateTimeField(verbose_name='Jadwal Praktek')),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=300)),
                ('kandungan', models.CharField(max_length=200)),
                ('khasiat', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_telepon', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=300)),
                ('keluhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Dokter')),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.DecimalField(decimal_places=3, max_digits=10)),
                ('kumpulan_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Obat')),
                ('nama_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Pasien')),
            ],
        ),
    ]
