# Generated by Django 3.0 on 2019-12-10 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=80)),
                ('tanggal', models.DateTimeField(default=datetime.datetime.now)),
                ('konten', models.TextField(max_length=2500)),
                ('komen', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
