# Generated by Django 3.0 on 2019-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('spesies', models.CharField(max_length=30)),
                ('berat', models.IntegerField(max_length=300)),
                ('umur', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('isi_kandang', models.CharField(max_length=30)),
                ('luas', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=30)),
                ('jadwal_jaga', models.DateField(verbose_name='Hari Berkunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=30)),
                ('jadwal_jaga', models.DateTimeField(verbose_name='Jadwal Jaga')),
            ],
        ),
    ]
